#!/bin/bash

if ! diff <(cat requirements.txt | sed 's/[>=]=[0-9].*//' | sort) <(pip freeze | sed 's/[>=]=[0-9].*//' | sort) ; then
	echo \'pip freeze\' and \'requirements.txt\' differ in their modules specified.
	echo Please fix this by running:
	echo "pip freeze | sed 's/==/>=/' >| requirements.txt"
	echo
	exit 1
fi

if black --version | grep -q Python ; then
	if ! black -l 79 --check -q ./*.py ; then
		echo Please format your files with:
		echo black -l 79 ./*.py
		echo \(You may need to install \'black\' first, if you haven\'t already.\)
		echo
		exit 2
	fi
fi

