#!/bin/bash

exit_code=0

if ! diff <(cat requirements.txt | sed 's/[>=]=[0-9].*//' | sort) <(pip freeze | sed 's/[>=]=[0-9].*//' | sort) ; then
	echo \'pip freeze\' and \'requirements.txt\' differ in their modules specified.
	echo Please fix this by running:
	echo "pip freeze | sed 's/==/>=/' >| requirements.txt"
	echo
	exit_code=$((exit_code+1))
fi

if black --version | grep -q Python ; then
	if ! black -l 79 --check -q ./*.py ; then
		echo Please format your files with:
		echo black -l 79 ./*.py
		echo \(You may need to install \'black\' first, if you haven\'t already.\)
		echo
		exit_code=$((exit_code+2))
	fi
fi

if [ $exit_code -gt 0 ] ; then
	echo Exit code:  $exit_code
	echo To commit without running this check, use:
	echo git commit --no-verify
else
	echo All is well\!
fi
exit $exit_code
